language: go
go:
- 1.6.3
addons:
  apt_packages:
    - libx11-dev
    - libgles2-mesa-dev
install:
- go get -t -d -v ./... && go build -v ./...
script:
- cd psiphon
- go test -v -covermode=count -coverprofile=transferstats.coverprofile ./transferstats
# upstreamproxy test disabled until "import cycle not allowed in test" problem resolved
#- go test -v -covermode=count -coverprofile=upstreamproxy.coverprofile ./upstreamproxy
- go test -v -covermode=count -coverprofile=server.coverprofile ./server
- go test -v -covermode=count -coverprofile=psiphon.coverprofile
- $HOME/gopath/bin/gover
- $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
before_install:
- go get github.com/axw/gocov/gocov
- go get github.com/modocache/gover
- go get github.com/mattn/goveralls
- if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
- openssl aes-256-cbc -K $encrypted_bf83b4ab4874_key -iv $encrypted_bf83b4ab4874_iv
  -in psiphon/controller_test.config.enc -out psiphon/controller_test.config -d
